# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5spGUa5eq0-BAUa_AN4Vb-0ZAfjikfx
"""

n = int(input("Masukkan nilai n : "))
total = 0
for i in range(1,n+1):
    total += i
print(f"Jumlah bilangan dari 1 hingga {n} adalah {total}")