# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5spGUa5eq0-BAUa_AN4Vb-0ZAfjikfx
"""

r = float(input("Masukkan jari-jari : "))
luas = 3.14 * pow(r,2)
print("Luas lingkaran = ",luas)