# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5spGUa5eq0-BAUa_AN4Vb-0ZAfjikfx
"""

for i in range(1,11,2):
    print(i)